name: create release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Generate Changelog
        id: generate_changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Extract info from git tag
        id: extract_info
        run: |
          echo "::set-output name=date::$(git log -1 --date=short --format=%ad '${{ github.ref }}')"
          echo "::set-output name=commitish::$(git rev-list -n 1 ${{ github.ref }})"
          echo ::set-output name=tag_name::${GITHUB_REF/refs\/tags\//}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          # Pass extracted release date, release notes and version to the Action.
          release-date: ${{ steps.extrac_info.outputs.date }}
          release-notes: ${{ steps.generate_changelog.outputs.changelog }}
          latest-version: ${{ steps.extrac_info.outputs.tag_name }}
          compare-url-target-revision: ${{ steps.extrac_info.outputs.commitish }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Push updated CHANGELOG to release target branch.
          branch: ${{ steps.extrac_info.outputs.commitish }}
          commit_message: "docs: update CHANGELOG"
          file_pattern: CHANGELOG.md
